### ISSUE TITLE
meta todo: move 'additional-tests' into recipes

### ISSUE THREAD

**Issue by thermokarst** [qiime2/package-integration#13]
Right now we have our tests specified as alp "additional-tests" - we should move those into the recipe test section to reap the benefits of the revdep testing cron job.

**Comment by thermokarst** [comment]
Actually, this might not be necessary. I need to take a closer look at these logs, but at first glance, it looks like we might be set:

https://github.com/qiime2/package-integration/runs/3463870800?check_suite_focus=true

**Comment by lizgehret** [comment]
this was necessary for the new CI, and has been completed.
