### ISSUE TITLE
cron failures

### ISSUE THREAD

**Issue by Keegan-Evans** [qiime2/package-integration#71]

**Comment by lizgehret** [comment]
Hey @Keegan-Evans just looking through open issues on pkg-int - should we keep this issue open? Was the intended functionality to add comments for each cron failure?

**Comment by Keegan-Evans** [comment]
@lizgehret, lets keep this issue open, as you observed, the issue is simply here to collect all failure comments.

**Comment by lizgehret** [comment]
closing this since we are no longer monitoring.
